name: fitstack
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  http: 
  dio: 
  flutter_svg: 

  #OpenFoodFactsAPI Dep
  openfoodfacts: 
  qr_code_scanner: 

  #camera
  camera:
  image_picker:
  
  #UI
  material_floating_search_bar: 
  salomon_bottom_bar: 
  line_icons: 
  flutter_speed_dial: 
  textfield_tags: 
  timelines:
  google_fonts: 
  chart_sparkline: 
  sliding_up_panel:
  awesome_emojis: 
  flutter_snake_navigationbar:
  
  #state/flow managment
  hooks_riverpod: 
  flutter_hooks:
  
  #annotation
  freezed_annotation: ^0.14.3

  #Firebase/Firestore
  firebase_core: 
  firebase_auth:
  cloud_firestore: 
  firebase_storage:

  #touchable model
  xml: ^5.3.0
  touchable: ^1.0.0
  svg_path_parser: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: 
  json_serializable: 
  build_runner:
  analyzer: 

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/AppLogo/
    - assets/images/StudioLogo/
    - assets/images/BodyRecovery/

 
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
